# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  batch-protein-folding-cfn-module-proteinmpnn.yaml: Implement ProteinMPNN module.
Parameters:
  ApplicationName:
    Description: Name of the application, if applicable
    Type: String
    Default: "Unknown"
  CodeRepositoryUrl:
    Description: Clone URL for the CodeCommit repository
    Type: String
  CodeBuildEncryptionKey:
    Description: Encryption key for CodeBuild jobs  
    Type: String
  CodeBuildRoleArn:
    Description: IAM role for CodeBuild jobs
    Type: String
  StartCodeBuildLambdaArn:
    Description: Lambda function for building container repos
    Type: String      
  DeleteContainerRepoLambdaArn:
    Description: Lambda function for deleting container repos
    Type: String

Resources:

  ProteinMPNNContainerRegistry:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId" 
        - Key: SolutionId
          Value: SO9164  

  CodeBuildProjectProteinMPNN:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Build Docker container for ProteinMPNN algorithm on AWS Batch
      EncryptionKey: !Ref CodeBuildEncryptionKey
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        EnvironmentVariables:
          - Name: IMAGE_TAG
            Value: latest
          - Name: IMAGE_REPO_NAME
            Value: !Ref ProteinMPNNContainerRegistry
          - Name: ACCOUNT_ID
            Value: !Ref "AWS::AccountId"
          - Name: BUILD_CONTEXT
            Value: infrastructure/docker/proteinmpnn
        Image: aws/codebuild/standard:4.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ResourceAccessRole: !Ref CodeBuildRoleArn
      ServiceRole: !Ref CodeBuildRoleArn
      Source:
        BuildSpec: infrastructure/docker/buildspec.yaml
        GitCloneDepth: 1
        Location: !Ref CodeRepositoryUrl
        Type: CODECOMMIT
      SourceVersion: refs/heads/main
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId"   
        - Key: SolutionId
          Value: SO9164  

  StartProteinMPNNContainerBuild:
    Type: Custom::ResourceForBuildingContainer
    Properties:
      ServiceToken:
        Ref: StartCodeBuildLambdaArn
      ProjectName:
        Ref: CodeBuildProjectProteinMPNN  

  ProteinMPNNJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      ContainerProperties:
        Command:
          - "nvidia-smi"
        Image: !Sub "${ProteinMPNNContainerRegistry.RepositoryUri}:latest"
        LogConfiguration:
          LogDriver: awslogs
        MountPoints:
          - ContainerPath: /database
            ReadOnly: False
            SourceVolume: database          
        ResourceRequirements:
          - Type: VCPU
            Value: 8
          - Type: MEMORY
            Value: 16000
          - Type: GPU
            Value: 1
        Volumes:
          - Name: database
            Host:
              SourcePath: /fsx            
      PlatformCapabilities:
        - EC2
      PropagateTags: true
      RetryStrategy:
        Attempts: 3
      Tags:
        Application: !Ref ApplicationName
        StackId: !Ref "AWS::StackId"
        SolutionId: SO9164  
      Type: container

  DeleteProteinMPNNContainerRepo:
    Type: Custom::ResourceForDeletingECR
    Properties:
      ServiceToken:
        Ref: DeleteContainerRepoLambdaArn
      ContainerRepo:
        Ref: ProteinMPNNContainerRegistry

Outputs:
  ProteinMPNNJobDefinition:
    Description: Job definition for running ProteinMPNN jobs on GPU instances.
    Value:
      Ref: ProteinMPNNJobDefinition
  ProteinMPNNContainerURI:
    Description: ECR URI for ProteinMPNN container image.
    Value:
      Ref: ProteinMPNNContainerRegistry