# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  batch-protein-folding-cfn-module-alphafold2.yaml: Implement AlphaFold2 module.
Parameters:
  ApplicationName:
    Description: Name of the application, if applicable
    Type: String
    Default: "Unknown"
  CodeRepositoryUrl:
    Description: Clone URL for the CodeCommit repository
    Type: String
  CodeBuildEncryptionKey:
    Description: Encryption key for CodeBuild jobs  
    Type: String
  CodeBuildRoleArn:
    Description: IAM role for CodeBuild jobs
    Type: String
  StartCodeBuildLambdaArn:
    Description: Lambda function for building container repos
    Type: String  
  DeleteContainerRepoLambdaArn:
    Description: Lambda function for deleting container repos
    Type: String
  Timestamp:
    Description: Timestamp for the cfn deployment
    Type: Number
    Default: 9999999999    


Resources:

  AlphaFold2ContainerRegistry:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId"       
        - Key: SolutionId
          Value: SO9164  

  CodeBuildProjectAlphaFold2:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Build Docker container for AlphaFold 2 algorithm on AWS Batch
      EncryptionKey: !Ref CodeBuildEncryptionKey
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        EnvironmentVariables:
          - Name: IMAGE_TAG
            Value: latest
          - Name: IMAGE_REPO_NAME
            Value: !Ref AlphaFold2ContainerRegistry
          - Name: ACCOUNT_ID
            Value: !Ref "AWS::AccountId"
          - Name: BUILD_CONTEXT
            Value: infrastructure/docker/alphafold2  
        Image: aws/codebuild/standard:6.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ResourceAccessRole: !Ref CodeBuildRoleArn
      ServiceRole: !Ref CodeBuildRoleArn
      Source:
        BuildSpec: infrastructure/docker/buildspec.yaml
        GitCloneDepth: 1
        Location: !Ref CodeRepositoryUrl
        Type: CODECOMMIT
      SourceVersion: refs/heads/main
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId"           
        - Key: SolutionId
          Value: SO9164  

  StartAlphaFold2ContainerBuild:
    Type: Custom::ResourceForBuildingContainer
    Properties:
      ServiceToken:
        Ref: StartCodeBuildLambdaArn
      ProjectName:
        Ref: CodeBuildProjectAlphaFold2                
      Timestamp:
        Ref: Timestamp

  AlphaFold2JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      ContainerProperties:
        Command:
          - "nvidia-smi"
        # Environment:
        #   - Name: TF_FORCE_UNIFIED_MEMORY
        #     Value: 1
        #   - Name: XLA_PYTHON_CLIENT_MEM_FRACTION
        #     Value: 4.0
        Image: !Sub "${AlphaFold2ContainerRegistry.RepositoryUri}:latest"
        LogConfiguration:
          LogDriver: awslogs
        MountPoints:
          - ContainerPath: /database
            ReadOnly: True
            SourceVolume: database
        ResourceRequirements:
          - Type: VCPU
            Value: 8
          - Type: MEMORY
            Value: 16000
          # - Type: GPU
          #   Value: 1
        Volumes:
          - Name: database
            Host:
              SourcePath: /fsx
      PlatformCapabilities:
        - EC2
      PropagateTags: true
      RetryStrategy:
        Attempts: 3
      Tags:
        Application: !Ref ApplicationName
        StackId: !Ref "AWS::StackId"
        SolutionId: SO9164  
      Type: container    

  DeleteAlphaFold2ContainerRepo:
    Type: Custom::ResourceForDeletingECR
    Properties:
      ServiceToken:
        Ref: DeleteContainerRepoLambdaArn
      ContainerRepo:
        Ref: AlphaFold2ContainerRegistry

Outputs:
  AlphaFold2JobDefinition:
    Description: Job definition for running AlphaFold2 jobs on GPU instances.
    Value:
      Ref: AlphaFold2JobDefinition
  AlphaFold2ContainerURI:
    Description: ECR URI for AlphaFold2 container image.
    Value:
      Ref: AlphaFold2ContainerRegistry
  CodeBuildProject:
    Description: CodeBuildProject
    Value:
      Ref: CodeBuildProjectAlphaFold2