# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  batch-protein-folding-cfn-module-omegafold.yaml: Implement Omegafold module.
Parameters:
  ApplicationName:
    Description: Name of the application, if applicable
    Type: String
    Default: "Unknown"
  CodeRepoS3BucketName:
    Description: S3 Bucket Name to retrieve code zip
    Type: String
    Default: "aws-hcls-ml"
  CodeBuildEncryptionKey:
    Description: Encryption key for CodeBuild jobs  
    Type: String
  CodeBuildRoleArn:
    Description: IAM role for CodeBuild jobs
    Type: String
  StartCodeBuildLambdaArn:
    Description: Lambda function for building container repos
    Type: String      
  DeleteContainerRepoLambdaArn:
    Description: Lambda function for deleting container repos
    Type: String
  Timestamp:
    Description: Timestamp for the cfn deployment
    Type: Number
    Default: 9999999999    

Resources:

  OmegaFoldContainerRegistry:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId" 
        - Key: SolutionId
          Value: SO9164  

  CodeBuildProjectOmegaFold:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Build Docker container for OmegaFold algorithm on AWS Batch
      EncryptionKey: !Ref CodeBuildEncryptionKey
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        EnvironmentVariables:
          - Name: IMAGE_TAG
            Value: latest
          - Name: IMAGE_REPO_NAME
            Value: !Ref OmegaFoldContainerRegistry
          - Name: ACCOUNT_ID
            Value: !Ref "AWS::AccountId"
          - Name: BUILD_CONTEXT
            Value: infrastructure/docker/omegafold
        Image: aws/codebuild/standard:6.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ResourceAccessRole: !Ref CodeBuildRoleArn
      ServiceRole: !Ref CodeBuildRoleArn
      Source:
        BuildSpec: infrastructure/docker/buildspec.yaml
        Location: !Sub "${CodeRepoS3BucketName}/main/batch-protein-folding.zip"
        Type: S3
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId"   
        - Key: SolutionId
          Value: SO9164  

  StartOmegaFoldContainerBuild:
    Type: Custom::ResourceForBuildingContainer
    Properties:
      ServiceToken:
        Ref: StartCodeBuildLambdaArn
      ProjectName:
        Ref: CodeBuildProjectOmegaFold  
      Timestamp:
        Ref: Timestamp
        
  OmegaFoldJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      ContainerProperties:
        Command:
          - "nvidia-smi"
        Image: !Sub "${OmegaFoldContainerRegistry.RepositoryUri}:latest"
        LogConfiguration:
          LogDriver: awslogs
        MountPoints:
          - ContainerPath: /database
            ReadOnly: True
            SourceVolume: database          
        ResourceRequirements:
          - Type: VCPU
            Value: 8
          - Type: MEMORY
            Value: 16000
          - Type: GPU
            Value: 1
        Volumes:
          - Name: database
            Host:
              SourcePath: /fsx            
      PlatformCapabilities:
        - EC2
      PropagateTags: true
      RetryStrategy:
        Attempts: 3
      Tags:
        Application: !Ref ApplicationName
        StackId: !Ref "AWS::StackId"
        SolutionId: SO9164  
      Type: container

  DeleteOmegaFoldContainerRepo:
    Type: Custom::ResourceForDeletingECR
    Properties:
      ServiceToken:
        Ref: DeleteContainerRepoLambdaArn
      ContainerRepo:
        Ref: OmegaFoldContainerRegistry

Outputs:
  OmegaFoldJobDefinition:
    Description: Job definition for running OmegaFold jobs on GPU instances.
    Value:
      Ref: OmegaFoldJobDefinition
  OmegaFoldContainerURI:
    Description: ECR URI for OmegaFold container image.
    Value:
      Ref: OmegaFoldContainerRegistry
  CodeBuildProject:
    Description: CodeBuildProject
    Value:
      Ref: CodeBuildProjectOmegaFold      