# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  batch-protein-folding-cfn-module-jackhmmer.yaml: Implement Jackhmmer module.
Parameters:
  ApplicationName:
    Description: Name of the application, if applicable
    Type: String
    Default: "Unknown"
  CodeRepoS3BucketName:
    Description: S3 Bucket Name to retrieve code zip
    Type: String
    Default: "aws-hcls-ml"
  CodeBuildEncryptionKey:
    Description: Encryption key for CodeBuild jobs
    Type: String
  CodeBuildRoleArn:
    Description: IAM role for CodeBuild jobs
    Type: String
  StartCodeBuildLambdaArn:
    Description: Lambda function for building container repos
    Type: String      
  DeleteContainerRepoLambdaArn:
    Description: Lambda function for deleting container repos
    Type: String
  Timestamp:
    Description: Timestamp for the cfn deployment
    Type: Number
    Default: 9999999999    

Resources:

  JackhmmerContainerRegistry:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId"
        - Key: SolutionId
          Value: SO9164

  CodeBuildProjectJackhmmer:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Build Docker container for Jackhmmer algorithm on AWS Batch
      EncryptionKey: !Ref CodeBuildEncryptionKey
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        EnvironmentVariables:
          - Name: IMAGE_TAG
            Value: latest
          - Name: IMAGE_REPO_NAME
            Value: !Ref JackhmmerContainerRegistry
          - Name: ACCOUNT_ID
            Value: !Ref "AWS::AccountId"
          - Name: BUILD_CONTEXT
            Value: infrastructure/docker/jackhmmer  
        Image: aws/codebuild/standard:6.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ResourceAccessRole: !Ref CodeBuildRoleArn
      ServiceRole: !Ref CodeBuildRoleArn
      Source:
        BuildSpec: infrastructure/docker/buildspec.yaml
        Location: !Sub "${CodeRepoS3BucketName}/main/batch-protein-folding.zip"
        Type: S3
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId"   
        - Key: SolutionId
          Value: SO9164

  StartJackhmmerContainerBuild:
    Type: Custom::ResourceForBuildingContainer
    Properties:
      ServiceToken:
        Ref: StartCodeBuildLambdaArn
      ProjectName:
        Ref: CodeBuildProjectJackhmmer                 
      Timestamp:
        Ref: Timestamp
        
  JackhmmerJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      ContainerProperties:
        Command:
          - "echo hello"
        Image: !Sub "${JackhmmerContainerRegistry.RepositoryUri}:latest"
        LogConfiguration:
          LogDriver: awslogs
        MountPoints:
          - ContainerPath: /database
            ReadOnly: False
            SourceVolume: database
        ResourceRequirements:
          - Type: VCPU
            Value: 8
          - Type: MEMORY
            Value: 16000
        Volumes:
          - Name: database
            Host:
              SourcePath: /fsx
      PlatformCapabilities:
        - EC2
      PropagateTags: true
      RetryStrategy:
        Attempts: 3
      Tags:
        Application: !Ref ApplicationName
        StackId: !Ref "AWS::StackId"
        SolutionId: SO9164  
      Type: container

  DeleteJackhmmerContainerRepo:
    Type: Custom::ResourceForDeletingECR
    Properties:
      ServiceToken:
        Ref: DeleteContainerRepoLambdaArn
      ContainerRepo:
        Ref: JackhmmerContainerRegistry

Outputs:
  JackhmmerJobDefinition:
    Description: Job definition for running Jackhmmer jobs.
    Value:
      Ref: JackhmmerJobDefinition
  JackhmmerContainerURI:
    Description: ECR URI for Jackhmmer container image.
    Value:
      Ref: JackhmmerContainerRegistry
  CodeBuildProject:
    Description: CodeBuildProject
    Value:
      Ref: CodeBuildProjectJackhmmer      