# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  batch-protein-folding-cfn-notebook.yaml: Creates a SageMaker notebook instance.
Parameters:
  ApplicationName:
    Description: Name of the application, if applicable
    Type: String
    Default: Unknown
  DefaultSecurityGroupID:
    Description: The default security group ID for the VPC
    Type: String
  Subnet:
    Description: Subnet ID for the file system.
    Type: String
  CodeRepositoryURI:
    Description: Code repository URI
    Type: String
  S3BucketName:
    Description: Optional S3 Bucket Name
    Type: String
    Default: ""
          

Resources:
  ##################################################
  # SageMaker Notebook Instance
  ##################################################

  EncryptionKey:
    Type: "AWS::KMS::Key"
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                Fn::Join: [":", ["arn:aws:iam:", !Ref "AWS::AccountId", "root"]]
            Action:
              [
                "kms:Create*",
                "kms:Describe*",
                "kms:Enable*",
                "kms:List*",
                "kms:Put*",
                "kms:Update*",
                "kms:Revoke*",
                "kms:Disable*",
                "kms:Get*",
                "kms:Delete*",
                "kms:TagResource",
                "kms:UntagResource",
                "kms:ScheduleKeyDeletion",
                "kms:CancelKeyDeletion",
              ]
            Resource: "*"
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId"
        - Key: SolutionId
          Value: SO9164  

  SageMakerNotebookExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSageMakerFullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSCodeCommitReadOnly"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSCloudFormationReadOnlyAccess"
      Policies:
        - PolicyName: SubmitJob
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - batch:SubmitJob
                  - batch:DescribeJobs
                  - batch:ListJobs
                  - batch:TerminateJobs
                Resource: "*"
        - PolicyName: S3RWPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}/*
              - Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:PutBucketPolicy
                Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}

  BatchFoldNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      DirectInternetAccess: Enabled
      InstanceType: ml.t3.medium
      DefaultCodeRepository: !Ref CodeRepositoryURI
      KmsKeyId: !GetAtt EncryptionKey.Arn
      PlatformIdentifier: "notebook-al2-v2"
      RoleArn: !GetAtt SageMakerNotebookExecutionRole.Arn
      SubnetId: !Ref Subnet
      SecurityGroupIds:
        - !Ref DefaultSecurityGroupID
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: StackId
          Value: !Ref "AWS::StackId"
        - Key: SolutionId
          Value: SO9164  
