FROM public.ecr.aws/lambda/python:3.9

RUN yum install git unzip wget -y
RUN git clone --depth 1 https://github.com/dauparas/ProteinMPNN.git /opt/proteinmpnn

RUN pip3 install --upgrade pip --no-cache-dir \
    && pip3 install --upgrade --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu torch numpy

RUN wget -O "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm awscliv2.zip

WORKDIR /opt/proteinmpnn

COPY run.sh run.sh

ENTRYPOINT ["bash", "run.sh"]
